{ config, lib, pkgs, system, ... }:

let
  cfg = config.jvf.services.llm-proxy;
  isDarwin = builtins.match ".*-darwin" system != null;

  # Define the python environment
  pythonEnv = pkgs.python3.withPackages (ps: with ps; [
    fastapi
    uvicorn
    httpx
    python-dotenv
    rich
    pydantic
    cryptography
    aiofiles
    apscheduler
    jinja2
    colorlog
    litellm
    filelock
    aiohttp
  ]);

  # Define source
  src = pkgs.fetchFromGitHub {
    owner = "Mirrowel";
    repo = "LLM-API-Key-Proxy";
    rev = "main";
    hash =
      if isDarwin
      then "sha256-1r6d6nkycs3dli21dvbvi2gfad39gnspsjx952myw8skkav2jw2j"
      else "sha256-LUy/Et3Ew87eVCNygyMh+zsUU12k3cNDWo3jMgN+YEY=";
  };

  # State directory for writable files
  stateDir = "/var/lib/llm-proxy";

  # Define the package using writeShellScriptBin
  llmProxyPkg = pkgs.writeShellScriptBin "llm-proxy" ''
    set -euo pipefail

    # Create state directory structure
    mkdir -p ${stateDir}/{logs,oauth_creds}

    # Link source files to state directory
    for item in ${src}/*; do
      name=$(basename "$item")
      if [ ! -e "${stateDir}/$name" ]; then
        ln -sf "$item" "${stateDir}/$name"
      fi
    done

    # Generate .env file from sops secrets
    {
      echo "# Auto-generated by NixOS llm-proxy module"
      echo "# DO NOT EDIT - changes will be overwritten on service restart"
      echo ""
      echo "# === Proxy Settings ==="
      echo "PROXY_API_KEY=\"$(cat /run/secrets/llm_proxy_api_key)\""
      echo "SKIP_OAUTH_INIT_CHECK=true"
      echo ""
      echo "# === Gemini API Key ==="
      echo "GEMINI_API_KEY_1=\"$(cat /run/secrets/gemini_api_key)\""
      echo ""
      echo "# === OpenRouter ==="
      echo "OPENROUTER_API_KEY_1=\"$(cat /run/secrets/openrouter_api_key_code_agent)\""
      echo ""
      echo "# === Minimax ==="
      echo "MINIMAX_API_KEY_1=\"$(cat /run/secrets/minimax_api_key)\""
      echo ""
      echo "# === xAI (Z-AI) ==="
      echo "XAI_API_KEY_1=\"$(cat /run/secrets/z_ai_api_key)\""
      echo ""
      echo "# === Antigravity Account 1 ==="
      echo "ANTIGRAVITY_REFRESH_TOKEN_1=\"$(cat /run/secrets/antigravity_account_1_refresh_token)\""
      echo "ANTIGRAVITY_EMAIL_1=\"$(cat /run/secrets/antigravity_account_1_email)\""
      echo ""
      echo "# === Antigravity Account 2 ==="
      echo "ANTIGRAVITY_REFRESH_TOKEN_2=\"$(cat /run/secrets/antigravity_account_2_refresh_token)\""
      echo "ANTIGRAVITY_EMAIL_2=\"$(cat /run/secrets/antigravity_account_2_email)\""
      echo ""
      echo "# === Advanced Settings ==="
      echo "ROTATION_MODE_ANTIGRAVITY=sequential"
      echo "MAX_CONCURRENT_REQUESTS_PER_KEY_ANTIGRAVITY=1"
    } > ${stateDir}/.env

    chmod 600 ${stateDir}/.env

    cd ${stateDir}
    exec ${pythonEnv}/bin/uvicorn src.proxy_app.main:app --host 0.0.0.0 "$@"
  '';

in
{
  options.jvf.services.llm-proxy = {
    enable = lib.mkEnableOption "LLM API Key Proxy";

    port = lib.mkOption {
      type = lib.types.port;
      default = 18000;
      description = "Port to run the proxy on.";
    };

    package = lib.mkOption {
      type = lib.types.package;
      default = llmProxyPkg;
      description = "The llm-proxy package to use.";
    };
  };

  config = lib.mkIf cfg.enable (lib.mkMerge [
    # Sops secrets declarations
    {
      sops.secrets = {
        llm_proxy_api_key = {
          mode = "0400";
        };
        gemini_api_key = {
          mode = "0400";
        };
        openrouter_api_key_code_agent = {
          mode = "0400";
        };
        minimax_api_key = {
          mode = "0400";
        };
        z_ai_api_key = {
          mode = "0400";
        };
        antigravity_account_1_refresh_token = {
          mode = "0400";
        };
        antigravity_account_1_email = {
          mode = "0400";
        };
        antigravity_account_2_refresh_token = {
          mode = "0400";
        };
        antigravity_account_2_email = {
          mode = "0400";
        };
      };
    }

    # NixOS Service
    (lib.optionalAttrs (!isDarwin) {
      systemd.services.llm-proxy = {
        description = "LLM API Key Proxy Service";
        wantedBy = [ "multi-user.target" ];
        after = [ "network.target" ];
        wants = [ "network-online.target" ];
        serviceConfig = {
          ExecStart = "${lib.getExe cfg.package} --port ${toString cfg.port}";
          Restart = "always";
          Type = "simple";
          StateDirectory = "llm-proxy";
          WorkingDirectory = "/var/lib/llm-proxy";
        };
      };
    })

    # Darwin Service
    (lib.optionalAttrs isDarwin {
      launchd.agents.llm-proxy = {
        serviceConfig = {
          ProgramArguments = [
            "${lib.getExe cfg.package}"
            "--port"
            (toString cfg.port)
          ];
          KeepAlive = true;
          RunAtLoad = true;
          StandardErrorPath = "/tmp/llm-proxy.err";
          StandardOutPath = "/tmp/llm-proxy.out";
        };
      };
    })
  ]);
}
