backend = "fastresize"
color_space = "labmixed"
palette = "dark16"
threshold = 11

[templates]
cava.template = 'colors-cava'
cava.target = '~/.config/cava/config'
hypr.template = 'colors-hyprland.conf'
hypr.target = '~/.config/hypr/wallust/wallust-hyprland.conf'
rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/wallust/colors-rofi.rasi'
kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/kitty/kitty-colors.conf'
