# Aspect: desktop-hyprland-ags (NixOS only)
# AGS - Awesome Hyprland Widgets. Packages + wrapper configs.
# Theme adapter: generates user/theme-colors.css from jvf.theme.colors.
_: {
  flake.modules.nixos.desktop-hyprland-ags =
    { config
    , lib
    , pkgs
    , ...
    }:
    let
      cfg = config.jvf.desktop.hyprland.ags;
      colors = config.jvf.theme.colors;

      # Theme adapter: generate AGS CSS custom properties
      agsThemeCss = pkgs.writeText "theme-colors.css" ''
        /* Generated by jvf.theme — do not edit manually */

        :root {
          --theme-background: #${colors.background};
          --theme-foreground: #${colors.foreground};
          --theme-cursor: #${colors.cursor};

          --theme-color0: #${colors.color0};
          --theme-color1: #${colors.color1};
          --theme-color2: #${colors.color2};
          --theme-color3: #${colors.color3};
          --theme-color4: #${colors.color4};
          --theme-color5: #${colors.color5};
          --theme-color6: #${colors.color6};
          --theme-color7: #${colors.color7};
          --theme-color8: #${colors.color8};
          --theme-color9: #${colors.color9};
          --theme-color10: #${colors.color10};
          --theme-color11: #${colors.color11};
          --theme-color12: #${colors.color12};
          --theme-color13: #${colors.color13};
          --theme-color14: #${colors.color14};
          --theme-color15: #${colors.color15};
        }
      '';
    in
    {
      options.jvf.desktop.hyprland.ags = {

        username = lib.mkOption {
          type = lib.types.str;
          default = config.jvf.core.username;
          description = "Username to configure AGS for.";
        };
      };

      config = {
        jvf.wrappers.users.${cfg.username}.programs.ags = {
          packages = [
            pkgs.ags
          ];
          configs = {
            "ags" = ./assets/ags;
          };
          postInstall = ''
            # Theme adapter: inject generated CSS custom properties
            mkdir -p "$TARGET_PATH/user"
            cp ${agsThemeCss} "$TARGET_PATH/user/theme-colors.css"
          '';
        };
      };
    };
}
