# Aspect: desktop-hyprland-ags (NixOS only)
# AGS - Awesome Hyprland Widgets. Packages + wrapper configs.
# Theme adapter: generates user/theme-colors.css from jvf.theme.colors.
_: {
  flake.modules.nixos.desktop-hyprland-ags =
    { config
    , lib
    , pkgs
    , ...
    }:
    let
      cfg = config.jvf.desktop.hyprland.ags;
      colors = config.jvf.theme.colors;
      darkPreset = config.jvf.theme.presets.tokyonight-night;
      lightPreset = config.jvf.theme.presets.tokyonight-day;

      # Theme adapter: generate AGS CSS custom properties from a color set
      mkAgsThemeCss = c: pkgs.writeText "theme-colors.css" ''
        /* Generated by jvf.theme — do not edit manually */

        :root {
          --theme-background: #${c.background};
          --theme-foreground: #${c.foreground};
          --theme-cursor: #${c.cursor};

          --theme-color0: #${c.color0};
          --theme-color1: #${c.color1};
          --theme-color2: #${c.color2};
          --theme-color3: #${c.color3};
          --theme-color4: #${c.color4};
          --theme-color5: #${c.color5};
          --theme-color6: #${c.color6};
          --theme-color7: #${c.color7};
          --theme-color8: #${c.color8};
          --theme-color9: #${c.color9};
          --theme-color10: #${c.color10};
          --theme-color11: #${c.color11};
          --theme-color12: #${c.color12};
          --theme-color13: #${c.color13};
          --theme-color14: #${c.color14};
          --theme-color15: #${c.color15};
        }
      '';

      # Active theme deployment (unchanged behavior)
      agsThemeCss = mkAgsThemeCss colors;

      # Profile artifacts for dual-theme runtime switching
      darkAgsArtifact = pkgs.runCommand "theme-ags-dark" { } ''
        mkdir -p $out
        cp ${mkAgsThemeCss darkPreset.colors} $out/theme-colors.css
      '';
      lightAgsArtifact = pkgs.runCommand "theme-ags-light" { } ''
        mkdir -p $out
        cp ${mkAgsThemeCss lightPreset.colors} $out/theme-colors.css
      '';
    in
    {
      options.jvf.desktop.hyprland.ags = {

        username = lib.mkOption {
          type = lib.types.str;
          default = config.jvf.core.username;
          description = "Username to configure AGS for.";
        };
      };

      config = {
        jvf.wrappers.users.${cfg.username}.programs.ags = {
          packages = [
            pkgs.ags
          ];
        };

        jvf.home.users.${cfg.username}.items.".config/ags" = {
          kind = "dir";
          mode = "copy";
          source = ./assets/ags;
          postInstall = ''
            # Theme adapter: inject generated CSS custom properties
            mkdir -p "$TARGET_PATH/user"
            cp ${agsThemeCss} "$TARGET_PATH/user/theme-colors.css"
          '';
        };

        # Profile artifacts for dual-theme runtime switching
        jvf.theme.profileArtifacts.dark.ags = darkAgsArtifact;
        jvf.theme.profileArtifacts.light.ags = lightAgsArtifact;
      };
    };
}
