# Aspect: desktop-hyprland-hypr (NixOS only)
# Hyprland compositor configuration with hypridle, hyprlock, pyprland.
# Config files managed via jvf.home.
# Theme adapter: generates two colour files from jvf.theme.colors —
#   wallust/colors.lua            for the Hyprland Lua config (>= 0.55)
#   wallust/wallust-hyprland.conf for hyprlock, which still uses hyprlang
_:
let
  mkOptions =
    { config, lib, ... }:
    {
      options.jvf.desktop.hyprland.hypr = {
        username = lib.mkOption {
          type = lib.types.str;
          default = config.jvf.core.username;
          description = "Username for which to configure Hyprland wrapper";
        };
      };
    };

in
{
  flake.modules.nixos.desktop-hyprland-hypr =
    { config
    , lib
    , pkgs
    , ...
    }:
    let
      cfg = config.jvf.desktop.hyprland.hypr;
      colors = config.jvf.theme.colors;
      darkPreset = config.jvf.theme.presets.tokyonight-night;
      lightPreset = config.jvf.theme.presets.tokyonight-day;

      # Theme adapter: generate the Lua colour module consumed by the Hyprland
      # Lua config (UserConfigs/user-settings.lua, UserConfigs/decor-animations.lua).
      mkHyprColorsLua =
        c:
        let
          names = [
            "color0"
            "color1"
            "color2"
            "color3"
            "color4"
            "color5"
            "color6"
            "color7"
            "color8"
            "color9"
            "color10"
            "color11"
            "color12"
            "color13"
            "color14"
            "color15"
          ];
          entry = n: "    ${n} = \"rgb(${c.${n}})\",";
        in
        pkgs.writeText "colors.lua" ''
          -- Generated by modules/desktop/hyprland/hypr.nix from jvf.theme.colors.
          -- Do not edit: overwritten on activation and by jvf-theme-switch.
          return {
              background = "rgb(${c.background})",
              foreground = "rgb(${c.foreground})",
          ${lib.concatStringsSep "\n" (map entry names)}
              placeholderFg = "#${c.foreground}99",
          }
        '';

      # Theme adapter: generate hyprland color variables from a color set.
      # Still required by hyprlock (hyprlock-2k.conf sources this file and uses
      # $color11/$color12/$color13), which has not moved to Lua.
      mkHyprColorsConf = c: pkgs.writeText "wallust-hyprland.conf" ''
        $background = rgb(${c.background})
        $foreground = rgb(${c.foreground})
        $color0 = rgb(${c.color0})
        $color1 = rgb(${c.color1})
        $color2 = rgb(${c.color2})
        $color3 = rgb(${c.color3})
        $color4 = rgb(${c.color4})
        $color5 = rgb(${c.color5})
        $color6 = rgb(${c.color6})
        $color7 = rgb(${c.color7})
        $color8 = rgb(${c.color8})
        $color9 = rgb(${c.color9})
        $color10 = rgb(${c.color10})
        $color11 = rgb(${c.color11})
        $color12 = rgb(${c.color12})
        $color13 = rgb(${c.color13})
        $color14 = rgb(${c.color14})
        $color15 = rgb(${c.color15})
        $placeholderFg = ##${c.foreground}99
      '';

      # Active theme deployment (unchanged behavior)
      hyprColorsConf = mkHyprColorsConf colors;
      hyprColorsLua = mkHyprColorsLua colors;

      # Profile artifacts for dual-theme runtime switching. Each profile carries
      # both formats: colors.lua for the compositor, wallust-hyprland.conf for
      # hyprlock.
      mkHyprArtifact =
        name: preset:
        pkgs.runCommand "theme-hypr-${name}" { } ''
          mkdir -p $out
          cp ${mkHyprColorsLua preset.colors} $out/colors.lua
          cp ${mkHyprColorsConf preset.colors} $out/wallust-hyprland.conf
        '';
      darkHyprArtifact = mkHyprArtifact "dark" darkPreset;
      lightHyprArtifact = mkHyprArtifact "light" lightPreset;
    in
    {
      imports = [ mkOptions ];

      config = {
        services.hypridle.enable = false;

        programs.hyprland = {
          enable = true;
          xwayland.enable = true;
          package = pkgs.hyprland;
        };

        jvf.wrappers.users.${cfg.username}.programs.hypr = {
          packages = [
            pkgs.hypridle
            pkgs.hyprcursor
            pkgs.hyprlock
            pkgs.pyprland
          ];
        };

        jvf.home.users.${cfg.username}.items = {
          ".config/hypr" = {
            kind = "dir";
            mode = "copy";
            source = ./assets/hypr/.;
            postInstall = ''
              # Theme adapter: inject generated colors (replaces wallust runtime gen)
              mkdir -p "$TARGET_PATH/wallust"
              # colors.lua is consumed by the Hyprland Lua config; the hyprlang
              # file is still read by hyprlock (hyprlock-2k.conf sources it).
              cp ${hyprColorsLua} "$TARGET_PATH/wallust/colors.lua"
              cp ${hyprColorsConf} "$TARGET_PATH/wallust/wallust-hyprland.conf"

              # Create Battery.sh script for hyprlock
              mkdir -p "$TARGET_PATH/scripts"
              cat > "$TARGET_PATH/scripts/Battery.sh" << 'BATTERY_EOF'
              #!/usr/bin/env bash
              # Battery status script for hyprlock

              if command -v acpi &> /dev/null; then
                  acpi -b | grep -P -o '[0-9]+(?=%)'
              elif [ -f /sys/class/power_supply/BAT0/capacity ]; then
                  cat /sys/class/power_supply/BAT0/capacity
              elif [ -f /sys/class/power_supply/BAT1/capacity ]; then
                  cat /sys/class/power_supply/BAT1/capacity
              else
                  echo "N/A"
              fi
              BATTERY_EOF

              # Make all scripts executable
              find "$TARGET_PATH/scripts" "$TARGET_PATH/UserScripts" -type f -name "*.sh" -exec chmod +x {} \; 2>/dev/null || true
              if [ -n "''${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; then
                echo "Reloading Hyprland..."
                ${config.programs.hyprland.package}/bin/hyprctl reload >/dev/null 2>&1 || true
              fi
            '';
          };
          ".config/pypr" = {
            kind = "dir";
            mode = "copy";
            source = ./assets/pypr/.;
          };
        };

        # Profile artifacts for dual-theme runtime switching
        jvf.theme.profileArtifacts.dark.hypr = darkHyprArtifact;
        jvf.theme.profileArtifacts.light.hypr = lightHyprArtifact;

        fonts.packages = [
          pkgs.nerd-fonts.jetbrains-mono
        ];
      };
    };
}
