# Aspect: desktop-hyprland-rofi (NixOS only)
# Rofi application launcher with Hyprland theming.
# Theme adapter: generates wallust/colors-rofi.rasi from jvf.theme.
_: {
  flake.modules.nixos.desktop-hyprland-rofi =
    { lib
    , config
    , pkgs
    , ...
    }:
    let
      cfg = config.jvf.desktop.hyprland.rofi;
      colors = config.jvf.theme.colors;
      rofi = config.jvf.theme.rofiSemantic;
      darkPreset = config.jvf.theme.presets.tokyonight-night;
      lightPreset = config.jvf.theme.presets.tokyonight-day;

      # Convert 6-char hex to "R,G,B" for rgba()
      hexToRgba =
        hex: a:
        let
          hexToInt =
            c:
            let
              chars = {
                "0" = 0;
                "1" = 1;
                "2" = 2;
                "3" = 3;
                "4" = 4;
                "5" = 5;
                "6" = 6;
                "7" = 7;
                "8" = 8;
                "9" = 9;
                "a" = 10;
                "b" = 11;
                "c" = 12;
                "d" = 13;
                "e" = 14;
                "f" = 15;
                "A" = 10;
                "B" = 11;
                "C" = 12;
                "D" = 13;
                "E" = 14;
                "F" = 15;
              };
            in
            chars.${c};
          h = builtins.substring;
          toNum = off: hexToInt (h off 1 hex) * 16 + hexToInt (h (off + 1) 1 hex);
        in
        "${toString (toNum 0)},${toString (toNum 2)},${toString (toNum 4)},${a}";

      # Theme adapter: generate rofi color definitions from color + semantic sets
      mkRofiColorsRasi = c: r: pkgs.writeText "colors-rofi.rasi" ''
        /* Generated by jvf.theme — do not edit manually */
        * {
        active-background: #${r.activeBackground};
        active-foreground: #${r.activeForeground};
        normal-background: #${r.normalBackground};
        normal-foreground: #${r.normalForeground};
        urgent-background: #${r.urgentBackground};
        urgent-foreground: #${r.urgentForeground};
        alternate-active-background: #${c.color11};
        alternate-active-foreground: #${r.activeForeground};
        alternate-normal-background: #${r.normalBackground};
        alternate-normal-foreground: #${r.normalForeground};
        alternate-urgent-background: #${r.normalBackground};
        alternate-urgent-foreground: #${r.normalForeground};
        selected-active-background: #${r.selectedBackground};
        selected-active-foreground: #${r.selectedForeground};
        selected-normal-background: #${r.selectedBackground};
        selected-normal-foreground: #${r.selectedForeground};
        selected-urgent-background: #${r.activeBackground};
        selected-urgent-foreground: #${r.activeForeground};
        background-color: #${r.normalBackground};
        background: rgba(${hexToRgba c.background "0.7"});
        foreground: #${r.normalForeground};
        border-color: #${r.borderColor};
        color0: #${c.color0};
        color1: #${c.color1};
        color2: #${c.color2};
        color3: #${c.color3};
        color4: #${c.color4};
        color5: #${c.color5};
        color6: #${c.color6};
        color7: #${c.color7};
        color8: #${c.color8};
        color9: #${c.color9};
        color10: #${c.color10};
        color11: #${c.color11};
        color12: #${c.color12};
        color13: #${c.color13};
        color14: #${c.color14};
        color15: #${c.color15};
        }
      '';

      # Active theme deployment (unchanged behavior)
      rofiColorsRasi = mkRofiColorsRasi colors rofi;

      # Profile artifacts for dual-theme runtime switching
      darkRofiArtifact = pkgs.runCommand "theme-rofi-dark" { } ''
        mkdir -p $out
        cp ${mkRofiColorsRasi darkPreset.colors darkPreset.rofiSemantic} $out/colors-rofi.rasi
      '';
      lightRofiArtifact = pkgs.runCommand "theme-rofi-light" { } ''
        mkdir -p $out
        cp ${mkRofiColorsRasi lightPreset.colors lightPreset.rofiSemantic} $out/colors-rofi.rasi
      '';
    in
    {
      options.jvf.desktop.hyprland.rofi = {
        username = lib.mkOption {
          type = lib.types.str;
          default = config.jvf.core.username;
          description = "Username for which to configure rofi wrapper";
        };
      };
      config = {
        jvf.wrappers.users.${cfg.username}.programs.rofi = {
          packages = [
            pkgs.rofi
          ];
        };

        jvf.home.users.${cfg.username}.items.".config/rofi" = {
          kind = "dir";
          mode = "copy";
          source = ./assets/rofi/.;
          postInstall = ''
            # Theme adapter: inject generated colors (replaces wallust runtime gen)
            mkdir -p "$TARGET_PATH/wallust"
            cp ${rofiColorsRasi} "$TARGET_PATH/wallust/colors-rofi.rasi"
          '';
        };

        # Profile artifacts for dual-theme runtime switching
        jvf.theme.profileArtifacts.dark.rofi = darkRofiArtifact;
        jvf.theme.profileArtifacts.light.rofi = lightRofiArtifact;
      };
    };
}
