# Aspect: desktop-hyprland-rofi (NixOS only)
# Rofi application launcher with Hyprland theming.
# Theme adapter: generates wallust/colors-rofi.rasi from jvf.theme.
_: {
  flake.modules.nixos.desktop-hyprland-rofi =
    { lib
    , config
    , pkgs
    , ...
    }:
    let
      cfg = config.jvf.desktop.hyprland.rofi;
      colors = config.jvf.theme.colors;
      rofi = config.jvf.theme.rofiSemantic;

      # Convert 6-char hex to "R,G,B" for rgba()
      hexToRgba =
        hex: a:
        let
          hexToInt =
            c:
            let
              chars = {
                "0" = 0;
                "1" = 1;
                "2" = 2;
                "3" = 3;
                "4" = 4;
                "5" = 5;
                "6" = 6;
                "7" = 7;
                "8" = 8;
                "9" = 9;
                "a" = 10;
                "b" = 11;
                "c" = 12;
                "d" = 13;
                "e" = 14;
                "f" = 15;
                "A" = 10;
                "B" = 11;
                "C" = 12;
                "D" = 13;
                "E" = 14;
                "F" = 15;
              };
            in
            chars.${c};
          h = builtins.substring;
          toNum = off: hexToInt (h off 1 hex) * 16 + hexToInt (h (off + 1) 1 hex);
        in
        "${toString (toNum 0)},${toString (toNum 2)},${toString (toNum 4)},${a}";

      # Theme adapter: generate rofi color definitions
      rofiColorsRasi = pkgs.writeText "colors-rofi.rasi" ''
        /* Generated by jvf.theme — do not edit manually */

        * {
        active-background: #${rofi.activeBackground};
        active-foreground: #${rofi.activeForeground};
        normal-background: #${rofi.normalBackground};
        normal-foreground: #${rofi.normalForeground};
        urgent-background: #${rofi.urgentBackground};
        urgent-foreground: #${rofi.urgentForeground};

        alternate-active-background: #${colors.color11};
        alternate-active-foreground: #${rofi.activeForeground};
        alternate-normal-background: #${rofi.normalBackground};
        alternate-normal-foreground: #${rofi.normalForeground};
        alternate-urgent-background: #${rofi.normalBackground};
        alternate-urgent-foreground: #${rofi.normalForeground};

        selected-active-background: #${rofi.selectedBackground};
        selected-active-foreground: #${rofi.selectedForeground};
        selected-normal-background: #${rofi.selectedBackground};
        selected-normal-foreground: #${rofi.selectedForeground};
        selected-urgent-background: #${rofi.activeBackground};
        selected-urgent-foreground: #${rofi.activeForeground};

        background-color: #${rofi.normalBackground};
        background: rgba(${hexToRgba colors.background "0.7"});
        foreground: #${rofi.normalForeground};
        border-color: #${rofi.borderColor};

        color0: #${colors.color0};
        color1: #${colors.color1};
        color2: #${colors.color2};
        color3: #${colors.color3};
        color4: #${colors.color4};
        color5: #${colors.color5};
        color6: #${colors.color6};
        color7: #${colors.color7};
        color8: #${colors.color8};
        color9: #${colors.color9};
        color10: #${colors.color10};
        color11: #${colors.color11};
        color12: #${colors.color12};
        color13: #${colors.color13};
        color14: #${colors.color14};
        color15: #${colors.color15};

        }
      '';
    in
    {
      options.jvf.desktop.hyprland.rofi = {
        username = lib.mkOption {
          type = lib.types.str;
          default = config.jvf.core.username;
          description = "Username for which to configure rofi wrapper";
        };
      };

      config = {
        jvf.wrappers.users.${cfg.username}.programs.rofi = {
          packages = [
            pkgs.rofi
          ];
          configs = {
            "rofi" = ./assets/rofi/.;
          };
          postInstall = ''
            # Theme adapter: inject generated colors (replaces wallust runtime gen)
            mkdir -p "$TARGET_PATH/wallust"
            cp ${rofiColorsRasi} "$TARGET_PATH/wallust/colors-rofi.rasi"
          '';
        };
      };
    };
}
