# Aspect: desktop-hyprland-waybar (NixOS only)
# Waybar status bar for Hyprland. Packages + jvf.home config + fonts.
# Theme adapter: generates wallust/colors-waybar.css from jvf.theme.colors.
_: {
  flake.modules.nixos.desktop-hyprland-waybar =
    { config
    , lib
    , pkgs
    , ...
    }:
    let
      cfg = config.jvf.desktop.hyprland.waybar;
      colors = config.jvf.theme.colors;
      alpha = config.jvf.theme.backgroundAlpha;

      # Theme adapter: generate waybar CSS color variables
      waybarColorsCss = pkgs.writeText "colors-waybar.css" ''
        /* Generated by jvf.theme — do not edit manually */

        @define-color foreground #${colors.foreground};
        @define-color background rgba(${hexToRgba colors.background alpha});
        @define-color cursor #${colors.cursor};

        @define-color color0 #${colors.color0};
        @define-color color1 #${colors.color1};
        @define-color color2 #${colors.color2};
        @define-color color3 #${colors.color3};
        @define-color color4 #${colors.color4};
        @define-color color5 #${colors.color5};
        @define-color color6 #${colors.color6};
        @define-color color7 #${colors.color7};
        @define-color color8 #${colors.color8};
        @define-color color9 #${colors.color9};
        @define-color color10 #${colors.color10};
        @define-color color11 #${colors.color11};
        @define-color color12 #${colors.color12};
        @define-color color13 #${colors.color13};
        @define-color color14 #${colors.color14};
        @define-color color15 #${colors.color15};
      '';

      # Convert 6-char hex to "R,G,B" for rgba()
      hexToRgba =
        hex: a:
        let
          hexToInt =
            c:
            let
              chars = {
                "0" = 0;
                "1" = 1;
                "2" = 2;
                "3" = 3;
                "4" = 4;
                "5" = 5;
                "6" = 6;
                "7" = 7;
                "8" = 8;
                "9" = 9;
                "a" = 10;
                "b" = 11;
                "c" = 12;
                "d" = 13;
                "e" = 14;
                "f" = 15;
                "A" = 10;
                "B" = 11;
                "C" = 12;
                "D" = 13;
                "E" = 14;
                "F" = 15;
              };
            in
            chars.${c};
          h = builtins.substring;
          toNum = off: hexToInt (h off 1 hex) * 16 + hexToInt (h (off + 1) 1 hex);
        in
        "${toString (toNum 0)},${toString (toNum 2)},${toString (toNum 4)},${a}";
    in
    {
      options.jvf.desktop.hyprland.waybar = {

        username = lib.mkOption {
          type = lib.types.str;
          default = config.jvf.core.username;
          description = "Username for which to configure waybar wrapper";
        };
      };

      config = {
        programs.waybar.enable = true;

        jvf.wrappers.users.${cfg.username}.programs.waybar = {
          packages = [
            pkgs.waybar
          ];
        };

        # Config via jvf.home — dir copy + wallust color injection
        jvf.home.users.${cfg.username}.items.".config/waybar" = {
          kind = "dir";
          mode = "copy";
          source = ./assets/waybar/.;
          postInstall = ''
            mkdir -p "$TARGET_PATH/wallust"
            cp ${waybarColorsCss} "$TARGET_PATH/wallust/colors-waybar.css"
          '';
        };

        fonts.packages = [
          pkgs.nerd-fonts.jetbrains-mono
          pkgs.font-awesome
        ];
      };
    };
}
