# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, host, pkgs, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
    supportedFilesystems = [ "btrfs" ];
    kernelPackages = pkgs.linuxPackages_latest; # Kernel

    kernelParams = [
      "systemd.mask=systemd-vconsole-setup.service"
      "systemd.mask=dev-tpmrm0.device" #this is to mask that stupid 1.5 mins systemd bug
      "nowatchdog"
      "modprobe.blacklist=sp5100_tco" #watchdog for AMD
      "modprobe.blacklist=iTCO_wdt" #watchdog for Intel
    ];

    initrd = {
      availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
      kernelModules = [ ];
    };

    kernel.sysctl = {
      "vm.max_map_count" = 2147483642;
    };

    loader = {
      systemd-boot.enable = false;

      efi.canTouchEfiVariables = true;

      timeout = 1;

      grub = {
        enable = true;
        device = "nodev";
        efiSupport = true;
        configurationLimit = 10;
      };
    };

    tmp = {
      useTmpfs = false;
      tmpfsSize = "30%";
    };

    plymouth.enable = true;
  };

  services.btrfs.autoScrub = { enable = true; interval = "monthly"; fileSystems = [ "/" ]; };

  distro-grub-themes = {
    enable = true;
    theme = "nixos";
  };

  fileSystems."/" =
    {
      device = "/dev/disk/by-partlabel/nixos-root";
      fsType = "btrfs";
      options = [ "subvol=@root" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-partlabel/nixos-root";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:5" "noatime" "autodefrag" ];
    };

  fileSystems."/nix"  =
    {
      device = "/dev/disk/by-partlabel/nixos-root";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-partlabel/boot";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
      neededForBoot = true;
    };

  fileSystems."/mnt/external_storage" = {
    device = "/dev/disk/by-partlabel/file-storage";
    fsType = "btrfs";
    options = [ "defaults" "noatime" "compress=zstd" "noatime" "autodefrag" ];
  };

  swapDevices =
    [{ device = "/dev/disk/by-partlabel/swap"; }];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.i2c.enable = true;
}
