# See https://wiki.hyprland.org/Configuring/Keywords/ for more settings variables

$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserConfigs = $HOME/.config/hypr/UserConfigs

# disabling Touchpad. use 'hyprctl devices' to get device name.
$Touchpad_Device = asue1209:00-04f3:319f-touchpad

binde = , xf86KbdBrightnessDown, exec, $scriptsDir/BrightnessKbd.sh --dec # Keyboard brightness Down
binde = , xf86KbdBrightnessUp, exec, $scriptsDir/BrightnessKbd.sh --inc # Keyboard brightness Up
bind = , xf86Launch1, exec, rog-control-center # ASUS Armory crate button
bind = , xf86Launch3, exec, asusctl led-mode # FN+F4 Switch keyboard RGB profile
bind = , xf86Launch4, exec, asusctl profile # FN+F5 change fan profiles (Quiet, Balance, Performance)
binde = , xf86MonBrightnessDown, exec, $scriptsDir/Brightness.sh --dec
binde = , xf86MonBrightnessUp, exec, $scriptsDir/Brightness.sh --inc
bind = , xf86TouchpadToggle, exec, $scriptsDir/TouchPad.sh # disable touchpad

# Screenshot keybindings for Asus G15 (no PrintScr button)
bind = $mainMod, F6, exec, $scriptsDir/ScreenShot.sh --now # Fullscreen
bind = $mainMod SHIFT, F6, exec, $scriptsDir/ScreenShot.sh --area
bind = $mainMod CTRL, F6, exec, $scriptsDir/ScreenShot.sh --in5 # Screenshot in 5 secs
bind = $mainMod ALT, F6, exec, $scriptsDir/ScreenShot.sh --in10 # Screenshot in 10 secs
bind = ALT, F6, exec, $scriptsDir/ScreenShot.sh --active # Screenshot active window

$TOUCHPAD_ENABLED = true
device {
    name = $Touchpad_Device
    enabled = $TOUCHPAD_ENABLED
}

# Below is useful when connecting laptop to external display.
# Suggest editing below laptop display.
# WIKI: disable laptop monitor when lid closed.
# consult https://wiki.hyprland.org/hyprland-wiki/pages/Configuring/Binds/#switches
#bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, preferred, auto, 1"
#bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"

#
# WARNING! Using this method has some caveats!! USE WITH CAUTION!
# CONS of doing this: wallpaper (SUPER+W) will re-choose wallpaper.
# CAVEATS! Main Laptop Monitor will NOT display. Needs re-connect external monitor.
# One work around: ensure before shutting down laptop, MAKE SURE laptop lid is OPEN!!
# Make sure to comment (put # on both bindl switch ......) above.
# NOTE: Display laptop generated in LaptopDisplay.conf
# If part of it is not used, you may not want main laptop monitor to wake during say wallpaper change etc.
#

#bindl = , switch:off:Lid Switch, exec, echo "monitor eDP-1, preferred, auto, 1" > $UserConfigs/LaptopDisplay.conf
#bindl = , switch:on:Lid Switch, exec, echo "monitor eDP-1, disable" > $UserConfigs/LaptopDisplay.conf

# laptop-lid action (to erase last entry)
#exec-once = echo "monitor eDP-1, preferred, auto, 1" > $HOME/.config/hypr/UserConfigs/LaptopDisplay.conf
