# See https://wiki.hyprland.org/Configuring/Keywords/ for more settings variables
# See Laptops.conf for laptop keybinds

$mainMod = SUPER

$files = kitty --class=yazi-fm -e yazi
$term = kitty
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts

# rofi App launcher
# bindr = $mainMod, $mainMod_L, exec, pkill rofi; rofi -show drun -modi drun,filebrowser,run,window # Super Key Launch rofi menu
bind = $mainMod, D, exec, pkill rofi; rofi -show drun -modi drun

# ags overview
bind = $mainMod, A, exec, pkill rofi || true && ags -t 'overview'

bind = $mainMod, Return, exec, $term # Launch terminal
bind = $mainMod, Y, exec, $scriptsDir/ToggleYazi.sh
bind = $mainMod, T, exec, $scriptsDir/ToggleTodo.sh # Edit Todo.md
bind = $mainMod, N, exec, $scriptsDir/ToggleQuickNote.sh # Edit quick-notes.md

bind = $mainMod ALT, C, exec, $UserScripts/RofiCalc.sh # calculator (qalculate)

# pyprland
bind = $mainMod SHIFT, Return, exec, pypr toggle term # Dropdown terminal
bind = $mainMod, Z, exec, pypr zoom # Toggle Zoom

# User Added Keybinds
bind = $mainMod SHIFT, O, exec, $UserScripts/ZshChangeTheme.sh # Change oh-my-zsh theme
bindn = ALT_L, SHIFT_L, exec, $scriptsDir/SwitchKeyboardLayout.sh # Changing the keyboard layout
bind = $mainMod SHIFT, Y, exec, $UserScripts/TodoAdd.sh # Add todo item via rofi
bind = $mainMod SHIFT, D, exec, $UserScripts/TodoCheck.sh # Complete todo item via rofi

# passthrough keyboard
# bind = $mainMod ALT, submap, passthru
# submap passthru
# unbind
# bind = $mainMod ALT, submap, reset
# submap reset
