# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more settings variables

# yazi file manager
windowrule match:class ^(yazi-fm)$, float on, size 900 600, center on, workspace special:yazi silent

# todo-nvim
windowrule match:class ^(todo-nvim)$, float on, size 900 600, center on, workspace special:todo silent

# quick-note-nvim
windowrule match:class ^(quick-note-nvim)$, float on, size 900 600, center on, workspace special:quick-note silent
