# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Yazi file manager floating scratchpad
windowrule = match:class ^(yazi-fm)$, float on, center on, size 900 600, workspace special:yazi silent

# Todo scratchpad floating neovim
windowrule = match:class ^(todo-nvim)$, float on, center on, size 900 600, workspace special:todo silent

# Quick note scratchpad floating neovim
windowrule = match:class ^(quick-note-nvim)$, float on, center on, size 900 600, workspace special:quick-note silent
