aliases:
  dp: deployments
  jo: jobs
  cr: clusterroles
  crb: clusterrolebindings
  ro: roles
  rb: rolebindings
  np: networkpolicies
  na: namespaces
  prod: namespaces production
  stag: namespaces staging
  self: namespaces self-hosted
  ctx: contexts
  home: contexts homelab
  sec: secrets all
  cm: configmap
  ss: statefulset
